from typing import Any, Callable

class TreeliteError(RuntimeError): ...

__version__: str

def register_callback_log_info(callback: Callable[[str], None]) -> None: ...
def register_callback_log_warning(callback: Callable[[str], None]) -> None: ...
def load_xgboost_model(filename: str, config: str) -> Any: ...
def dump_as_json(model: Any, pretty_print: bool) -> str: ...
