/*!
 * Copyright (c) 2017-2023 by Contributors
 * \file c_api.h
 * \author Hyunsu Cho
 * \brief C API of Treelite, used for interfacing with other languages
 */

/* Note: Make sure to use slash-asterisk form of comments in this file
   (like this one). Do not use double-slash (//). */

#ifndef TREELITE_C_API_H_
#define TREELITE_C_API_H_

#ifdef __cplusplus
#define TREELITE_EXTERN_C extern "C"
#include <cstdint>
#include <cstdio>
#else
#define TREELITE_EXTERN_C
#include <stdint.h>
#include <stdio.h>
#endif

/* Special symbols for DLL library on Windows */
#if defined(_MSC_VER) || defined(_WIN32)
#define TREELITE_DLL TREELITE_EXTERN_C __declspec(dllexport)
#else
#define TREELITE_DLL TREELITE_EXTERN_C __attribute__((visibility("default")))
#endif

/*!
 * \addtogroup opaque_handles
 * Opaque handles
 * \{
 */
/*! \brief Handle to a decision tree ensemble model */
typedef void* TreeliteModelHandle;
/*! \brief Handle to a configuration of GTIL predictor */
typedef void* TreeliteGTILConfigHandle;
/*! \} */

/*!
 * \defgroup model_loader Model loaders for XGBoost and LightGBM
 * \{
 */
/*!
 * \brief Load a model file generated by XGBoost (dmlc/xgboost), stored in the legacy binary
 *        format.
 * \param filename Name of model file
 * \param config_json JSON string consisting key-value pairs; used for configuring the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadXGBoostModelLegacyBinary(
    char const* filename, char const* config_json, TreeliteModelHandle* out);
/*!
 * \brief Load an XGBoost model from a memory buffer using the legacy binary format.
 * \param buf Memory buffer
 * \param len Size of memory buffer
 * \param config_json Null-terminated JSON string consisting key-value pairs; used for configuring
 *                    the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadXGBoostModelLegacyBinaryFromMemoryBuffer(
    void const* buf, size_t len, char const* config_json, TreeliteModelHandle* out);
/*!
 * \brief Load a model file generated by XGBoost (dmlc/xgboost), stored in the JSON format.
 * \param filename Name of model file
 * \param config_json Null-terminated JSON string consisting key-value pairs; used for configuring
 *                    the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadXGBoostModel(
    char const* filename, char const* config_json, TreeliteModelHandle* out);
/*!
 * \brief Load an XGBoost model from a JSON string
 * \param json_str JSON string containing the XGBoost model
 * \param length Length of the JSON string
 * \param config_json Null-terminated JSON string consisting key-value pairs; used for configuring
 *                    the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadXGBoostModelFromString(
    char const* json_str, size_t length, char const* config_json, TreeliteModelHandle* out);
/*!
 * \brief Load a model file generated by LightGBM (Microsoft/LightGBM). The
 *        model file must contain a decision tree ensemble.
 * \param filename Name of model file
 * \param config_json Null-terminated JSON string consisting key-value pairs; used for configuring
 *                    the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadLightGBMModel(
    char const* filename, char const* config_json, TreeliteModelHandle* out);
/*!
 * \brief Load a LightGBM model from a string. The string should be created with the
 *        model_to_string() method in LightGBM.
 * \param model_str Model string
 * \param config_json Null-terminated JSON string consisting key-value pairs; used for configuring
 *                    the model parser
 * \param out Loaded model
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteLoadLightGBMModelFromString(
    char const* model_str, char const* config_json, TreeliteModelHandle* out);
/*! \} */

/*!
 * \defgroup model_manager Functions to query and modify model objects
 * \{
 */
/*!
 * \brief Dump a model object as a JSON string
 * \param handle The handle to the model object
 * \param pretty_print Whether to pretty-print JSON string (0 for false, != 0 for true)
 * \param out_json_str The JSON string
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteDumpAsJSON(
    TreeliteModelHandle handle, int pretty_print, char const** out_json_str);
/*!
 * \brief Query the input type of a Treelite model object
 * \param model Treelite Model object
 * \param out_str String representation of input type
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGetInputType(TreeliteModelHandle model, char const** out_str);
/*!
 * \brief Query the output type of a Treelite model object
 * \param model Treelite Model object
 * \param out_str String representation of output type
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGetOutputType(TreeliteModelHandle model, char const** out_str);
/*!
 * \brief Query the number of trees in the model
 * \param model Model to query
 * \param out Number of trees
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteQueryNumTree(TreeliteModelHandle model, size_t* out);
/*!
 * \brief Query the number of features used in the model
 * \param model Model to query
 * \param out Number of features
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteQueryNumFeature(TreeliteModelHandle model, int* out);
/*!
 * \brief Delete model from memory
 * \param handle Model to remove
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteFreeModel(TreeliteModelHandle handle);
/*! \} */

/*!
 * \defgroup gtil General Tree Inference Library (GTIL), providing a reference implementation for
 * predicting with decision trees. GTIL is useful in cases it is infeasible to build the
 * tree models as native shared libs.
 * \{
 */

/*!
 * \brief Load a configuration for GTIL predictor from a JSON string.
 * \param config_json a JSON string with the following fields:
 *   - "nthread" (optional): Number of threads used for initializing DMatrix.
 *                           Set <= 0 to use all CPU cores.
 *   - "predict_type" (required): Must be one of the following.
 *     - "default": Sum over trees and apply post-processing
 *     - "raw": Sum over trees, but don't apply post-processing; get raw margin scores instead.
 *     - "leaf_id": Output one (integer) leaf ID per tree.
 *     - "score_per_tree": Output one or more margin scores per tree.
 * \param out Parsed configuration
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGTILParseConfig(char const* config_json, TreeliteGTILConfigHandle* out);

/*!
 * \brief Delete a GTIL configuration from memory
 * \param handle Handle to the GTIL configuration to be deleted
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGTILDeleteConfig(TreeliteGTILConfigHandle handle);

/*!
 * \brief Given a batch of data rows, query the necessary shape of array to hold predictions for all
 *        data points.
 * \param model Treelite Model object
 * \param num_row Number of rows in the input
 * \param config Configuration of GTIL predictor. Set this by calling \ref TreeliteGTILParseConfig.
 * \param out_shape Array of dimensions
 * \param out_ndim Number of dimensions in out_shape
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGTILGetOutputShape(TreeliteModelHandle model, uint64_t num_row,
    TreeliteGTILConfigHandle config, uint64_t const** out, uint64_t* out_ndim);

/*!
 * \brief Predict with a 2D dense array
 * \param model Treelite Model object
 * \param input The 2D data array, laid out in row-major layout
 * \param num_row Number of rows in the data matrix.
 * \param output Pointer to buffer to store the output. Call \ref TreeliteGTILGetOutputShape to get
 *               the amount of buffer you should allocate for this parameter.
 * \param config Configuration of GTIL predictor. Set this by calling \ref TreeliteGTILParseConfig.
 * \return 0 for success; -1 for failure
 */
TREELITE_DLL int TreeliteGTILPredict(TreeliteModelHandle model, void const* input,
    char const* input_type, uint64_t num_row, void* output, TreeliteGTILConfigHandle config);

/*! \} */

/*!
 * \brief Display last error; can be called by multiple threads
 * Note. Each thread will get the last error occured in its own context.
 * \return Error string
 */
TREELITE_DLL char const* TreeliteGetLastError(void);

/*!
 * \brief Register callback function for LOG(INFO) messages -- helpful messages
 *        that are not errors.
 * Note: This function can be called by multiple threads. The callback function
 *       will run on the thread that registered it
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteRegisterLogCallback(void (*callback)(char const*));

/*!
 * \brief Register callback function for LOG(WARNING) messages
 * Note: This function can be called by multiple threads. The callback function
 *       will run on the thread that registered it
 * \return 0 for success, -1 for failure
 */
TREELITE_DLL int TreeliteRegisterWarningCallback(void (*callback)(char const*));

#endif  // TREELITE_C_API_H_
